/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ems;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class gpa extends javax.swing.JFrame {
         DefaultTableModel model;
    /**
     * Creates new form gpa
     */
    public gpa() {
        initComponents();
        setResults();
    }
    
    public void setResults(){
        try {
             Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("select * from results");
             
             
             while (rs.next()) {
                 String module_id = rs.getString("module_id");
                 String moduleName = rs.getString("module_name");
                 String student_id = rs.getString("student_id");
                 String grade = rs.getString("grade");
                 String gpa = rs.getString("gpa");
                 
                 Object[] obj = {module_id, moduleName,student_id, grade, gpa };
                 model = (DefaultTableModel)jTable1.getModel(); 
                 model.addRow(obj);
                
            }
             
         
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        reg1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(204, 204, 255));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg1.setFont(new java.awt.Font("Apple Braille", 0, 24)); // NOI18N
        head.add(reg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 12, -1, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grades");
        head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 18, -1, -1));

        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 500, 70));

        body.setBackground(new java.awt.Color(204, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbtn.setBackground(new java.awt.Color(153, 204, 255));
        backbtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        body.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 116, 48));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "module_id", "Module name", "Student_id", "Grade", "Gpa"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 476, 219));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 500, 300));

        setSize(new java.awt.Dimension(519, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Profile ob = new Profile();
        ob.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gpa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JPanel body;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel reg1;
    // End of variables declaration//GEN-END:variables
}
